theme = "manjaro-homepage"
baseurl = "/"
languageCode = "en-us"
title = "Manjaro - enjoy the simplicity"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
#enableGitInfo = true
publishDir = "../docs"
themesDir = "../.."
i18nDir = "../i18n/"
assetDir = "../static/"
DefaultContentLanguage = "en-us"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    website_version = "1.0.30"
    background = "/img/header.jpg"
    tint = "green"
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    meta_description = "Free fast and secure Linux based operating system for everyone, suitable replacement to Windows or MacOS with different Desktop Environments"
    meta_keywords = "manjaro linux, based on arch linux, free operating system"

[params.download_edition]
    download_x64_title = "64 bit version"
    download_x86_title = "32 bit version"
    download_button = "Download"
    download_button_minimal = "Download Minimal"
    download_minimal_description = "Only a minimal set of packages are installed for a basic Desktop Environment, no additional applications are pre-installed."
    download_x64_description = "Only 64 bit is available for modern hardware, if you looking for legacy 32 bit go "
    download_x86_description = "Download the 32 bit version if you use an older computer or if you are unsure if your computer supports the 64 bit version."
    download_gpg = "Download GPG signature"
    download_torrent = "Download Torrent"

# --- Top Menu

[[menu.main]]
    name = "News"
    url = "/news/"
    pre = ""
    weight = 5

[[menu.main]]
    name = "Shop"
    url = "#"
    pre = ""
    weight = 4
    identifier = "shop"

[[menu.main]]
    name = "Donate"
    pre = ""
    url = "/donate/"
    weight = 3 

[[menu.main]]
    name = "Downloads"
    url = "/download/"
    pre = ""
    weight = 1

[[menu.main]]
    name = "Features"
    url = "#"
    pre = ""
    weight = 2
    identifier = "features"

[[menu.main]]
    name = "More"
    url = "#"
    pre = ""
    identifier = "more"
    weight = 6

#
# --- End Top Menu ---
#

# --- SubMenu More ---

[[menu.main]]
    name = "Packages"
    url = "https://repo.manjaro.org/"
    pre = ""
    weight = 3
    parent = "more"
    identifier = "packages"

[[menu.main]]
    name = "Support"
    url = "#"
    pre = ""
    weight = 2
    parent = "more"
    identifier = "support"

[[menu.main]]
    name = "About"
    url = "#"
    pre = ""
    weight = 4
    parent = "more"
    identifier = "about"

[[menu.main]]
    name = "Lists"
    url = "#"
    pre = ""
    weight = 2
    identifier = "mailinglists"
    parent = "more"
#
# --- End SubMenu Others 
#

# --- SubMenu about ---

[[menu.main]]
    name = "Team"
    url = "/team/"
    pre = "<i class='fa fa-users'></i></i>"
    weight = 1
    parent = "about"

[[menu.main]]
    name = "Linux"
    url = "/linux/"
    pre = "<i class='fab fa-linux'></i></i>"
    weight = 2
    parent = "about"

# --- SubMenu Support ---

[[menu.main]]
    name = "First Steps"
    url = "/support/firststeps/"
    pre = "<i class='fas fa-shoe-prints'></i></i>"
    weight = 1
    parent = "support"


[[menu.main]]
    name = "Common Problems"
    url = "/support/commonproblems/"
    pre = "<i class='fas fa-ambulance'></i></i>"
    weight = 2
    parent = "support"


[[menu.main]]
    name = "User Guide"
    url = "/support/userguide/"
    pre = "<i class='fas fa-book-open'></i></i>"
    weight = 2
    parent = "support"


[[menu.main]]
    name = "Forum"
    url = "https://forum.manjaro.org/"
    pre = "<i class='fas fa-hands-helping'></i></i>"
    weight = 3
    parent = "support"


[[menu.main]]
    name = "Wiki"
    url = "https://wiki.manjaro.org"
    pre = "<i class='fas fa-user-graduate'></i>"
    weight = 5
    parent = "support"

#
# --- End SubMenu Support 
#

# --- Submenu Shop ---

[[menu.main]]
    name = "Merch & Accessories"
    url = "https://shop.spreadshirt.de/manjaro/"
    pre = "<i class='fas fa-tshirt'></i>"
    weight = 1
    parent = "shop"


[[menu.main]]
    name = "Manjaro Stickers"
    url = "https://linux-aarhus.dk/en/product-category/manjaro-en/stickers-en/"
    pre = "<i class='fas fa-ticket-alt'></i>"
    weight = 2
    parent = "shop"


[[menu.main]]
    name = "Hardware - Notebooks & PCs"
    url = "https://www.ubuntushop.be/index.php/en/opensource-notebooks/manjaro-notebooks.html"
    pre = "<i class='fas fa-desktop'></i>"
    weight = 5
    parent = "shop"


#[[menu.main]]
#    name = "Hardware - Spitfire"
#    url = "/hardware-spitfire"
#    pre = "<i class='fas fa-laptop'></i>"
#    weight = 4
#    parent = "shop"


# [[menu.main]]
#    name = "Hardware - Bladebook"
#    url = "/hardware-bladebook"
#    pre = ""
#    weight = 3
#    parent = "shop"

#
# --- End SubMenu Shop --- 
#

#
# --- Submenu Packages ---
#

[[menu.main]]
    name = "Mirrors"
    url = "https://repo.manjaro.org/"
    pre = "<i class='fas fa-globe'></i></i>"
    weight = 1
    parent = "packages"
    identifier = "mirrors"

#
# --- end submenu ---
#

# --- Submenu Lists ---

[[menu.main]]
    name = "Security"
    url = "https://lists.manjaro.org/mailman/listinfo/manjaro-security"
    pre = "<i class='fas fa-envelope'></i>"
    weight = 1
    parent = "mailinglists"

[[menu.main]]
    name = "General"
    url = "https://lists.manjaro.org/mailman/listinfo/manjaro-general"
    pre = "<i class='fas fa-envelope'></i>"
    weight = 2
    parent = "mailinglists"


[[menu.main]]
    name = "Packages"
    url = "https://lists.manjaro.org/mailman/listinfo/manjaro-packages"
    pre = "<i class='fas fa-envelope'></i>"
    weight = 3
    parent = "mailinglists"


[[menu.main]]
    name = "Testing"
    url = "https://lists.manjaro.org/mailman/listinfo/manjaro-testing"
    pre = "<i class='fas fa-envelope'></i>"
    weight = 4
    parent = "mailinglists"


[[menu.main]]
    name = "Development"
    url = "https://lists.manjaro.org/mailman/listinfo/manjaro-dev"
    pre = "<i class='fas fa-envelope'></i>"
    weight = 5
    parent = "mailinglists"

[[menu.main]]
    name = "Mirrors"
    url = "https://lists.manjaro.org/mailman/listinfo/manjaro-mirrors"
    pre = "<i class='fas fa-envelope'></i>"
    weight = 6
    parent = "mailinglists"

#
# --- end Submenu Lists ---
#

# --- submenu Features ---

[[menu.main]]
    name = "Under your control"
    url = "/features/under-your-control/"
    pre = "<i class='fas fa-thumbs-up'></i></i>"
    weight = 2
    parent = "features"


[[menu.main]]
    name = "Configured with one click"
    url = "/features/configured-with-one-click/"
    pre = "<i class='fas fa-cog'></i></i>"
    weight = 3
    parent = "features"


[[menu.main]]
    name = "Useful for everyone"
    url = "/features/useful-for-everyone/"
    pre = "<i class='fas fa-users'></i>"
    weight = 4
    parent = "features"


[[menu.main]]
    name = "Fresh & Stable"
    url = "/features/fresh-and-stable/"
    pre = "<i class='fas fa-paper-plane'></i>"
    weight = 5
    parent = "features"

#
# --- end submenu Features ---
#

# --- others ---
 

[[menu.footer]]
    identifier = "copyright"
    name = "2019 Manjaro Linux"
    pre = "<i class='fa fa-copyright'></i>"
    url = "/"
    weight = 2


[[menu.footer]]
    identifier = "privacy"
    name = "Privacy Policy"
    pre = ""
    url = "/privacy-policy/"
    weight = 3


[[menu.footer]]
    identifier = "terms"
    name = "Terms of Use"
    pre = ""
    url = "/terms-of-use/"
    weight = 4


[[menu.footer]]
    identifier = "gitlab"
    pre = "<i class='fab fa-gitlab'></i>"
    url = "https://gitlab.manjaro.org"
    weight = 5

